### ISSUE TITLE
Bluetooth | Connect App to Device

### ISSUE THREAD

**Issue by stalberm** [Soundbendor/smart-bin-app#2]
We must be able to discover the Nano device as an open bluetooth connection, select it, and maintain a successful connection to it via bluetooth.

**Comment by theusaf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scan for Bluetooth Devices](https://trello.com/c/un1yM5jh/45-scan-for-bluetooth-devices)

**Comment by theusaf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get bluetooth search page to display connections](https://trello.com/c/fHYplHfe/44-get-bluetooth-search-page-to-display-connections)
