### ISSUE TITLE
UX | Create User Guide

### ISSUE THREAD

**Issue by theusaf** [Soundbendor/smart-bin-app#44]
## Description

As a user, I want to understand how to use the application so that I can quickly get to using and collecting data.

### Why?

The application will have many parts and features which may need explanations on how to use, or what they mean.

### Who?

This is intended for the end user.

## Solution/Requirements

This could be implemented in various ways.
* Tooltips/buttons that users can click to get an explanation about
* A page with various documents that a user can read to understand the application

## Dependencies

All major features implemented to a lovable degree.

## Additional System Graphics

![Image](https://github.com/Soundbendor/smart-bin-app/assets/73560521/7741e81e-14a1-4c81-976a-2b55ba37dedd)

**Comment by AbdoALPOP** [comment]
👋 Hey Daniel,

I am interested in your task and available to start immediately.

I am experienced with [Docusaurus.io](http://docusaurus.io/), [Nextra](https://nextra.site/), [Mkdocs](http://mkdocs.org/), and markdown. I can provide you with a user-friendly guide.

Here are some of my live guides:
- [Redstone](https://docs.redstone.finance/docs/introduction)
- [RHQ](https://documentation-orhp.vercel.app/)
- [WashMaster User Guide](https://help.dev.washmaster.ch/)

I'm looking forward to hearing from you soon 😃
[Contact me](mailto:abdoprogrammer55@gmail.com) and let's get started.

**Comment by kimberlymarkley** [comment]
Waiting on final specs from bin engineering team
