### ISSUE TITLE
Documentation | Create new visual of front end / back end architecture

### ISSUE THREAD

**Issue by kimberlymarkley** [Soundbendor/smart-bin-app#66]
## Description
As a developer, I need to have a thorough understanding of the app architecture so that I can easily maintain the code and add new features.

### Why?
We are committed to producing high quality code, and accompanying documentation that clearly outlines the app architecture.

### Who?
Donnelly, current & future app developers

## Solution/Requirements
* create a visual in Lucid chart 

## Definition of Done\
* A detailed overview of architecture, perhaps two separate graphics that resemble the level of detail represented here:

![Image](https://github.com/Soundbendor/smart-bin-app/assets/73560521/67b407ea-3d9f-4698-879e-c7cd810bed1e)
https://lucid.app/lucidchart/e33ee6b2-e8bb-4fb0-b114-d7f6d87e939e/edit?beaconFlowId=B24F1409A5D78343&page=0_0&invitationId=inv_0add0385-67ff-4ec7-aba1-48ede7808de3#

![Image](https://github.com/Soundbendor/smart-bin-app/assets/73560521/52339c7e-b91f-44a5-8686-825c7ad374d6)
https://lucid.app/lucidchart/958f4097-28e3-4fb8-bec2-66bf11735084/edit?page=0_0&invitationId=inv_668c4bc3-b253-4cc9-ae77-dc7fb832aa07#

**Comment by kimberlymarkley** [comment]
Link to current diagram
https://lucid.app/lucidchart/64e149fa-b9c0-48af-8eec-782f312da3f9/edit?invitationId=inv_cff6128e-8bb2-4846-ac9a-4a5de1de70fd&page=0_0#

**Comment by stalberm** [comment]
https://lucid.app/lucidchart/d0f5462b-511c-4588-99fc-e81eb21c6443/edit?page=0_0&invitationId=inv_a6b314fd-2c37-4c4d-b163-bd86ab7fb75b#
