### ISSUE TITLE
UI | Mock up Database Loading in Figma

### ISSUE THREAD

**Issue by kimberlymarkley** [Soundbendor/smart-bin-app#77]
## Description
As a bin user, I want to see a loading screen while the app is getting data from the database so that I know when the app is retrieving new records.

### Why?
Visual feedback is helpful for identifying whether the app is functioning correctly or not.

### Who?
Both users of the app and developers.

## Solution/Requirements

* [ ] When the bin is refreshing its data, a loading screen should appear.
* [ ] Loading screen lasts just as long as it needs to.

## Definition of Done
* [ ] While the user is waiting for a refresh to succeed, they are given a visual indicator.
* [ ] The loading screen functions properly with both Android and iOS.
* [ ] Required verifications from team members are made and relevant pull requests/commits are merged into dev/main.

**Comment by bpugh5** [comment]
Is this still relevant? I feel like all we'd really need to do is have the detections page show a loading icon until the detections are there... right?
